select 
"" as `Slave_IO_State`, 
t.source_id as `Master_Host`, 
"" as `Master_User`, 
0 as `Master_Port`, 
0 as `Connect_Retry`, 
concat("mysql-bin." ,substring_index(t.eventid, ':', 1)) as `Master_Log_File`, 
0 as `Read_Master_Log_Pos`, 
"" as `Relay_Log_File`, 
0 as `Relay_Log_Pos`, 
"" as `Relay_Master_Log_File`, 
"" as `Slave_IO_Running`, 
"" as `Slave_SQL_Running`, 
"" as `Replicate_Do_DB`, 
"" as `Replicate_Ignore_DB`, 
"" as `Replicate_Do_Table`, 
"" as `Replicate_Ignore_Table`, 
"" as `Replicate_Wild_Do_Table`, 
"" as `Replicate_Wild_Ignore_Table`, 
0 as `Last_Errno`, 
"" as `Last_Error`, 
0 as `Skip_Counter`, 
cast(substring_index(substring_index(t.eventid, ':', -1), ';', 1) as UNSIGNED)  
 as `Exec_Master_Log_Pos`, 
0 as `Relay_Log_Space`, 
"" as `Until_Condition`, 
"" as `Until_Log_File`, 
0 as `Until_Log_Pos`, 
"" as `Master_SSL_Allowed`, 
"" as `Master_SSL_CA_File`, 
"" as `Master_SSL_CA_Path`, 
"" as `Master_SSL_Cert`, 
"" as `Master_SSL_Cipher`, 
"" as `Master_SSL_Key`, 
round(greatest(0, cast(t.applied_latency as UNSIGNED)), 0) as `Seconds_Behind_Master`, 
"" as `Master_SSL_Verify_Server_Cert`, 
0 as `Last_IO_Errno`, 
"" as `Last_IO_Error`, 
0 as `Last_SQL_Errno`, 
"" as `Last_SQL_Error` 
from tungsten_%DATASERVICE%.trep_commit_seqno t 
  where t.applied_latency=
   (select max(applied_latency) from tungsten_%DATASERVICE%.trep_commit_seqno)
  limit 1;
